### ISSUE TITLE
Allow import of generated `_pb2.py`

### ISSUE THREAD

**Issue by Spellchaser** [trailofbits/protofuzz#61]
This may be a misunderstanding of how protobufs work.

If I have a compiled protobuf module, I can try to import the python file as a module

error as expected:
```
message_fuzzers = protofuzz.from_file("/Users/Spellchaser/PycharmProjects/test/module_pb2.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/protofuzz.py", line 251, in from_file
    module = pbimport.from_file(protobuf_file)
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/pbimport.py", line 114, in from_file
    raise BadProtobuf()
protofuzz.pbimport.BadProtobuf
```

**Comment by woodruffw** [comment]
Just to clarify: your goal here is to import the generated Python directly, rather than having the protobuf compiler do the generation for you under the hood?

If so, I think the option in #63 is the one we want, since it preserves the API surface.

**Comment by Spellchaser** [comment]
Correct, there's two use cases I'm encountering here

1. as a first time user, just makes it simpler for these scenarios
    1. I've generated the code directly already
    2. have the generated python code already and don't have the compiler installed
    3. want to run in this in a docker container with just the generated python code imported

2. More contrived but I have some weird system where the files won't exist as modules I can import, but I will provide a filepath to import the generated code.

**Comment by Spellchaser** [comment]
As to which option to pick, adding both is always an option.

I do think adding the handler to `from_file` might be better since python module means a lot more than loading just a file

The module loader was actually referenced in #11 
`module = pbimport._load_module(os.path.abspath('file_pb2.py'))`

**Comment by woodruffw** [comment]
Got it, thanks for the explanation. Yeah, we'll go with #63 for now.
