### ISSUE TITLE
Fix resource leaks caused by `pkg_resources`

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/protofuzz#65]
`protofuzz.values` currently uses the `pkg_resources` module from Setuptools to load package resources (i.e., `fuzzdb` assets). These APIs apparently don't make closing their underlying file handles easy, so we should switch to `importlib` for resource handling.

Example of the warning spew caused by the current `pkg_resources` usage:

```
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/http-protocol/user-agents.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/http-protocol/http-protocol-methods.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/http-protocol/crlf-injection.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/http-protocol/hpp.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/business-logic/DebugParams.Json.fuzz.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/business-logic/CommonDebugParamNames.txt'>
  source = _open_fuzzdb_file(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/william/devel/protofuzz/protofuzz/values.py:22: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/business-logic/CommonMethodNames.txt'>
  for value in stream:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
....../Users/william/devel/protofuzz/protofuzz/values.py:90: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/integer-overflow/integer-overflows.txt'>
  for num in _fuzzdb_integers(limit):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
......./Users/william/devel/protofuzz/protofuzz/tests/test_values.py:16: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/william/devel/protofuzz/protofuzz/fuzzdb/attack/rfi/rfi.txt'>
  vals = list(values.get_strings(limit=10))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
```

**Comment by jscanlannyc** [comment]
Hi,

I am interested in fixing this issue. I have a few smaller questions before I write an implementation, as I do not want to annoy with a bad PR. I am flexible on all these answers, I see some of these as improvements, but I also know that keeping the change small is more manageable.

1. Would it be OK if I replaced `.format()` with f-strings?
2. Would it be OK if I used `Pathlib` instead of strings for file location?
3. While resolving the location `fuzzdb` dependency with importlib, would you like this to potentially be configurable as an env variable (`os.environ`)? This is in case someone installs this via pip or does not `--recursively` clone the project or has a separate `fuzzdb` instance they maintain.

Please let me know. Thank you for your time.

**Comment by woodruffw** [comment]
Thanks for stating your interest!

> * Would it be OK if I replaced `.format()` with f-strings?
> * Would it be OK if I used `Pathlib` instead of strings for file location?

Yes, and yes! Please do these, any modernization would be greatly appreciated.

> 3\. While resolving the location `fuzzdb` dependency with importlib, would you like this to potentially be configurable as an env variable (`os.environ`)? This is in case someone installs this via pip or does not `--recursively` clone the project or has a separate `fuzzdb` instance they maintain.

Sounds good to me. This is definitely a usability annoyance at the moment.

> 4\. How do you feel about type annotations?

We love type annotations! Any you add here would also be greatly appreciated.

**Comment by jscanlannyc** [comment]
Thanks so much for the quick reply.

I have made my changes and would like to verify them against the test suite before issuing a PR. What is the suggested workflow for that? The nose website says it is in maintenance mode, should I use nose2? Something else?

**Comment by woodruffw** [comment]
Hmm, you shouldn't need either -- the tests under `protofuzz/tests` should be bog-standard `unittest`-based tests, meaning that the default built-in harness _should_ work:

```
python -m unittest protofuzz.tests
```

(I think that's the right syntax.)

**Comment by woodruffw** [comment]
Whoops, _this_ should work:

```bash
python -m unittest discover
```

**Comment by jscanlannyc** [comment]
Cool, that was helpful. I do have a PR ready that passed tests through this cmdline workflow:

```bash
python3 setup.py install; 
python3 -m unittest discover; 
```

I will issue the PR shortly.

**Comment by woodruffw** [comment]
Awesome! Feel free to give me a ping on it when you submit it.

**Comment by woodruffw** [comment]
#68.
